<!DOCTYPE html>
<html lang="ru">
<head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
        <meta http-equiv="imagetoolbar" content="false">
        <link rel="preload" href="./theme/fonts/lato-v14-latin-300.woff2" as="font" type="font/woff2" /><!--  crossorigin  -->
        <link rel="preload" href="./theme/fonts/lato-v14-latin-700.woff2" as="font" type="font/woff2" /><!--  crossorigin  -->
        <link rel="preload" href="./theme/css/screen.css" as="style">
        <link rel="preload" href="./theme/css/user.css" as="style">

        <link rel="icon" type="image/x-icon" href="/favicon.ico">
        <title>053. Обработка ошибок</title>

        <link rel="stylesheet" href="./theme/css/screen.css" />
        <link rel="stylesheet" href="./theme/css/user.css" />
        <!--[if lt IE 9]>
  <script src="./theme/js/html5shiv.min.js"></script>
  <script src="./theme/js/respond.min.js"></script>
  <![endif]-->
</head>

<body class="wrap js" id="page-top">
  <header>
    <div class="flexbox">
      <div class="center-on-mobiles">
        <h1>
          <a href="./" class="logo">
            <span class="sr-only">Azeevrt</span>
            <img src="./theme/img/logo-2x.png" width="140" height="65" alt="Azeevrt Logo">
          </a>
        </h1>
      </div>
      <nav class="main-nav hide-on-mobiles">
        <ul>
          <li>
              <a href="./category/azeevrt.html">Azeevrt</a>
          </li>
          <li class="active">
              <a href="./category/nodejs.html">Node.js</a>
          </li>
        </ul>
      </nav>
      <div class="meta hide-on-mobiles">
        <ul>
              <li><a href="https://azeevrt.github.io/site">Azeevrt /site/</a></li>
        </ul>
      </div>
    </div>
    <nav class="mobile-nav show-on-mobiles">
      <ul>
          <li>
              <a href="./category/azeevrt.html">Azeevrt</a>
          </li>
          <li class="active">
              <a href="./category/nodejs.html">Node.js</a>
          </li>
    </ul>
    </nav>
  </header>
    <section class="standalone">
      <div class="grid">
        <div class="unit whole">
          <article>
            <h3>53. Обработка ошибок</h3>
<p>Ошибки в Node.js обрабатываются с помощью исключений. </p>
<h5>Создание исключения</h5>
<p>Исключение создается с помощью ключевого слова throw. </p>
<div class="highlight"><pre><span></span><span class="err">throw value</span>
</pre></div>


<p>При достижении данной строки кода выполнение программы останавливается и управление передается ближайшему обработчику исключений. </p>
<p>Как правило, в клиентском коде value может быть любым допустимым типом данных, таким как строка, число или объект. </p>
<p>В Node.js мы выбрасываем только объекты ошибки. </p>
<h5>Объект ошибки</h5>
<p>Объект ошибки - это объект, который является либо экземпляром объекта Error, либо наследником класса Error, предоставляемого <a href="https://nodejs.org/api/errors.html">модулем Error</a>. </p>
<div class="highlight"><pre><span></span><span class="err">throw new Error(&#39;Ran out of coffee&#39;)</span>
</pre></div>


<p>Или </p>
<div class="highlight"><pre><span></span><span class="err">class NotEnoughCoffeeError extends Error {</span>
<span class="err">    // ...</span>
<span class="err">}</span>
<span class="err">throw new NotEnoughCoffeeError()</span>
</pre></div>


<h5>Обработка исключений</h5>
<p>Исключение обрабатывается в блоке try/catch. 
Любое исключение, возникшее в try, обрабатывается ближайшим catch. </p>
<div class="highlight"><pre><span></span><span class="err">try {</span>
<span class="err">    // ... </span>
<span class="err">} catch (e) {}</span>
</pre></div>


<p>'e' - это значение исключения. </p>
<p>Вы можете добавить несколько обработчиков для обработки разных ошибок. </p>
<h5>Обработка непойманных (неперехваченных) исключений</h5>
<p>Если в процессе выполнения программы возникнет неперехваченное исключение, выполнение программы остановится. </p>
<p>Для решения данной проблемы необходимо добавить обработчик события uncaughtException объекта process: </p>
<div class="highlight"><pre><span></span><span class="k">proc</span><span class="nb">es</span><span class="nv">s.on</span><span class="p">(</span><span class="s">&#39;uncaughtException&#39;</span><span class="p">,</span> <span class="nv">err</span> <span class="o">=&gt;</span> <span class="err">{</span>
    <span class="nf">console.error</span><span class="p">(</span><span class="s">&#39;There was an uncaught error&#39;</span><span class="p">,</span> <span class="nv">err</span><span class="p">)</span>
    <span class="k">proc</span><span class="nb">es</span><span class="nv">s.exit</span><span class="p">(</span><span class="mi">1</span><span class="p">)</span> <span class="o">//</span> <span class="err">вызов</span> <span class="err">данного</span> <span class="err">метода</span> <span class="err">является</span> <span class="err">обязательным</span>
<span class="err">})</span>
</pre></div>


<p>Получать модуль process не требуется, поскольку он внедрен по умолчанию. </p>
<h5>Исключения и промисы</h5>
<p>С помощью промисов можно выполнить разные операции и обработать ошибки в самом конце: </p>
<div class="highlight"><pre><span></span><span class="err">doSomething1()</span>
<span class="err">    .then(doSomething2)</span>
<span class="err">    .then(doSomething3)</span>
<span class="err">    .catch(err =&gt; console.error(err))</span>
</pre></div>


<p>Как узнать, где возникла ошибка? Для этого можно обрабатывать ошибки в каждой функции, которая вызывается (doSomethingX), и внутри обработчика ошибок выбрасывать новую ошибку, которая будет перехвачена внешним catch: </p>
<div class="highlight"><pre><span></span><span class="err">const doSomething1 = () =&gt; {</span>
<span class="err">    //...</span>
<span class="err">    try {</span>
<span class="err">        //...</span>
<span class="err">    } catch (err) {</span>
<span class="err">        //... обрабатываем ошибку локального</span>
<span class="err">        throw new Error(err.message)</span>
<span class="err">    }</span>
<span class="err">    //...</span>
<span class="err">}</span>
</pre></div>


<p>Для локальной обработки ошибок без их обработки внутри вызываемой функции, можно разорвать цепочку и создать в каждом <code>then()</code> специальную функцию:</p>
<div class="highlight"><pre><span></span><span class="nf">doSomething1</span><span class="p">()</span>
<span class="na">.then</span><span class="p">(()</span> <span class="err">=&gt;</span> <span class="err">{</span>
    <span class="nf">return</span> <span class="no">doSomething2</span><span class="p">().</span><span class="no">catch</span><span class="p">(</span><span class="no">err</span> <span class="err">=&gt;</span> <span class="err">{</span>
    <span class="c1">// обрабатываем ошибку</span>
    <span class="nf">throw</span> <span class="no">err</span> <span class="c1">// разрываем цепочку!</span>
    <span class="err">})</span>
<span class="err">})</span>
<span class="na">.then</span><span class="p">(()</span> <span class="err">=&gt;</span> <span class="err">{</span>
    <span class="nf">return</span> <span class="no">doSomething2</span><span class="p">().</span><span class="no">catch</span><span class="p">(</span><span class="no">err</span> <span class="err">=&gt;</span> <span class="err">{</span>
    <span class="c1">// обрабатываем ошибку</span>
    <span class="nf">throw</span> <span class="no">err</span> <span class="c1">// разрываем цепочку!</span>
    <span class="err">})</span>
<span class="err">})</span>
<span class="na">.catch</span><span class="p">(</span><span class="no">err</span> <span class="err">=&gt;</span> <span class="no">console.error</span><span class="p">(</span><span class="no">err</span><span class="p">))</span>
</pre></div>


<h5>Обработка ошибок с помощью async/await</h5>
<p>При использовании async/await вам также нужно обрабатывать ошибки: </p>
<div class="highlight"><pre><span></span><span class="err">async function someFunction() {</span>
<span class="err">    try {</span>
<span class="err">        await someOtherFunction()</span>
<span class="err">    } catch (err) {</span>
<span class="err">        console.error(err.message)</span>
<span class="err">    }</span>
<span class="err">}</span>
</pre></div>

          </article><!-- /#posts-list -->
        </div>
        <div class="clear"></div>
      </div>
    </section>
<footer>
  <div class="grid">
    <div class="unit one-third center-on-mobiles">
  <h2>Р</h2>
    <ul class="inline-block text align-center list">
          <li> — <a href="https://github.com/azeevrt/site.git" target="_top">репозиторий</a></li>
    </ul><!-- /.blogroll -->
    </div>
    <div class="unit two-thirds align-right center-on-mobiles">
      <p>
        Гордо принимает 
        <a href="https://github.com">
          <img src="./theme/img/footer-logo.png" width="100" height="30" alt="GitHub • Социальное программирование">
        </a>
      </p>
      <h2>A</h2>
        <ul class="inline-block text align-center list">
                <li> — <a href="https://azeevrt.github.io/site">Azeevrt /site/</a></li>
        </ul><!-- /.social -->
    </div>
  </div>
</footer>
<a class="scroll-to-top rounded js-scroll-trigger button" href="#"><i class="fas fa-angle-up"></i></a>
<script src="./theme/js/jquery-2.2.4.min.js"></script>
<script type="text/javascript">
    // Smooth scrolling using jQuery easing
    $('a.js-scroll-trigger[href*="#"]:not([href="#"])').click(function() {
      if (location.pathname.replace(/^\//, '') == this.pathname.replace(/^\//, '') && location.hostname == this.hostname) {
        var target = $(this.hash);
        target = target.length ? target : $('[name=' + this.hash.slice(1) + ']');
        if (target.length) {
          $('html, body').animate({
            scrollTop: target.offset().top
          }, 1000, "easeInOutExpo");
          return false;
        }
      }
    });


     $('.akkordeon').on('click', 'h2, h3, h4, strong', function () {
        var akk = $(this).parent().parent();
        var action;
        (!akk.attr('open')) ? action = 'expand': action = 'reduce';
        var section = 'page.module.part.' + action;

    });
</script>
</body>
</html>